from enum import Enum


class ContentIssueEnum(str, Enum):
    ILLEGAL_VARIABLE_IN_CONTROL_VALUE = "ILLEGAL_VARIABLE_IN_CONTROL_VALUE"
    INVALID_FILTER_ARG_IN_VARIABLE = "INVALID_FILTER_ARG_IN_VARIABLE"
    INVALID_URL = "INVALID_URL"
    MISSING_VALUE = "MISSING_VALUE"
    TIER_LIMIT_EXCEEDED = "TIER_LIMIT_EXCEEDED"

    def __str__(self) -> str:
        return str(self.value)
