from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.channel_settings_dto import ChannelSettingsDto
    from ..models.subscriber_response_dto_optional_data_type_0 import SubscriberResponseDtoOptionalDataType0


T = TypeVar("T", bound="SubscriberResponseDtoOptional")


@_attrs_define
class SubscriberResponseDtoOptional:
    """
    Attributes:
        field_id (str | Unset): The internal ID generated by Notifly for your subscriber. This ID does not match the
            `subscriberId` used in your queries. Refer to `subscriberId` for that identifier.
        first_name (None | str | Unset): The first name of the subscriber.
        last_name (None | str | Unset): The last name of the subscriber.
        email (None | str | Unset): The email address of the subscriber.
        phone (None | str | Unset): The phone number of the subscriber.
        avatar (None | str | Unset): The URL of the subscriber's avatar image.
        locale (None | str | Unset): The locale setting of the subscriber, indicating their preferred language or
            region.
        channels (list[ChannelSettingsDto] | Unset): An array of channel settings associated with the subscriber.
        topics (list[str] | Unset): An array of topics that the subscriber is subscribed to.
        is_online (bool | None | Unset): Indicates whether the subscriber is currently online.
        last_online_at (None | str | Unset): The timestamp indicating when the subscriber was last online, in ISO 8601
            format.
        field_v (float | Unset): The version of the subscriber document.
        data (None | SubscriberResponseDtoOptionalDataType0 | Unset): Additional custom data for the subscriber
        timezone (None | str | Unset): Timezone of the subscriber
    """

    field_id: str | Unset = UNSET
    first_name: None | str | Unset = UNSET
    last_name: None | str | Unset = UNSET
    email: None | str | Unset = UNSET
    phone: None | str | Unset = UNSET
    avatar: None | str | Unset = UNSET
    locale: None | str | Unset = UNSET
    channels: list[ChannelSettingsDto] | Unset = UNSET
    topics: list[str] | Unset = UNSET
    is_online: bool | None | Unset = UNSET
    last_online_at: None | str | Unset = UNSET
    field_v: float | Unset = UNSET
    data: None | SubscriberResponseDtoOptionalDataType0 | Unset = UNSET
    timezone: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.subscriber_response_dto_optional_data_type_0 import SubscriberResponseDtoOptionalDataType0

        field_id = self.field_id

        first_name: None | str | Unset
        if isinstance(self.first_name, Unset):
            first_name = UNSET
        else:
            first_name = self.first_name

        last_name: None | str | Unset
        if isinstance(self.last_name, Unset):
            last_name = UNSET
        else:
            last_name = self.last_name

        email: None | str | Unset
        if isinstance(self.email, Unset):
            email = UNSET
        else:
            email = self.email

        phone: None | str | Unset
        if isinstance(self.phone, Unset):
            phone = UNSET
        else:
            phone = self.phone

        avatar: None | str | Unset
        if isinstance(self.avatar, Unset):
            avatar = UNSET
        else:
            avatar = self.avatar

        locale: None | str | Unset
        if isinstance(self.locale, Unset):
            locale = UNSET
        else:
            locale = self.locale

        channels: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.channels, Unset):
            channels = []
            for channels_item_data in self.channels:
                channels_item = channels_item_data.to_dict()
                channels.append(channels_item)

        topics: list[str] | Unset = UNSET
        if not isinstance(self.topics, Unset):
            topics = self.topics

        is_online: bool | None | Unset
        if isinstance(self.is_online, Unset):
            is_online = UNSET
        else:
            is_online = self.is_online

        last_online_at: None | str | Unset
        if isinstance(self.last_online_at, Unset):
            last_online_at = UNSET
        else:
            last_online_at = self.last_online_at

        field_v = self.field_v

        data: dict[str, Any] | None | Unset
        if isinstance(self.data, Unset):
            data = UNSET
        elif isinstance(self.data, SubscriberResponseDtoOptionalDataType0):
            data = self.data.to_dict()
        else:
            data = self.data

        timezone: None | str | Unset
        if isinstance(self.timezone, Unset):
            timezone = UNSET
        else:
            timezone = self.timezone

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if field_id is not UNSET:
            field_dict["_id"] = field_id
        if first_name is not UNSET:
            field_dict["firstName"] = first_name
        if last_name is not UNSET:
            field_dict["lastName"] = last_name
        if email is not UNSET:
            field_dict["email"] = email
        if phone is not UNSET:
            field_dict["phone"] = phone
        if avatar is not UNSET:
            field_dict["avatar"] = avatar
        if locale is not UNSET:
            field_dict["locale"] = locale
        if channels is not UNSET:
            field_dict["channels"] = channels
        if topics is not UNSET:
            field_dict["topics"] = topics
        if is_online is not UNSET:
            field_dict["isOnline"] = is_online
        if last_online_at is not UNSET:
            field_dict["lastOnlineAt"] = last_online_at
        if field_v is not UNSET:
            field_dict["__v"] = field_v
        if data is not UNSET:
            field_dict["data"] = data
        if timezone is not UNSET:
            field_dict["timezone"] = timezone

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.channel_settings_dto import ChannelSettingsDto
        from ..models.subscriber_response_dto_optional_data_type_0 import SubscriberResponseDtoOptionalDataType0

        d = dict(src_dict)
        field_id = d.pop("_id", UNSET)

        def _parse_first_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        first_name = _parse_first_name(d.pop("firstName", UNSET))

        def _parse_last_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        last_name = _parse_last_name(d.pop("lastName", UNSET))

        def _parse_email(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        email = _parse_email(d.pop("email", UNSET))

        def _parse_phone(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        phone = _parse_phone(d.pop("phone", UNSET))

        def _parse_avatar(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        avatar = _parse_avatar(d.pop("avatar", UNSET))

        def _parse_locale(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        locale = _parse_locale(d.pop("locale", UNSET))

        _channels = d.pop("channels", UNSET)
        channels: list[ChannelSettingsDto] | Unset = UNSET
        if _channels is not UNSET:
            channels = []
            for channels_item_data in _channels:
                channels_item = ChannelSettingsDto.from_dict(channels_item_data)

                channels.append(channels_item)

        topics = cast(list[str], d.pop("topics", UNSET))

        def _parse_is_online(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        is_online = _parse_is_online(d.pop("isOnline", UNSET))

        def _parse_last_online_at(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        last_online_at = _parse_last_online_at(d.pop("lastOnlineAt", UNSET))

        field_v = d.pop("__v", UNSET)

        def _parse_data(data: object) -> None | SubscriberResponseDtoOptionalDataType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                data_type_0 = SubscriberResponseDtoOptionalDataType0.from_dict(data)

                return data_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | SubscriberResponseDtoOptionalDataType0 | Unset, data)

        data = _parse_data(d.pop("data", UNSET))

        def _parse_timezone(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        timezone = _parse_timezone(d.pop("timezone", UNSET))

        subscriber_response_dto_optional = cls(
            field_id=field_id,
            first_name=first_name,
            last_name=last_name,
            email=email,
            phone=phone,
            avatar=avatar,
            locale=locale,
            channels=channels,
            topics=topics,
            is_online=is_online,
            last_online_at=last_online_at,
            field_v=field_v,
            data=data,
            timezone=timezone,
        )

        subscriber_response_dto_optional.additional_properties = d
        return subscriber_response_dto_optional

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
